"""teams table

Revision ID: cb4e92ca37fc
Revises: 347efdaf84fa
Create Date: 2026-06-20 00:00:01.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID


# revision identifiers, used by Alembic.
revision = 'cb4e92ca37fc'
down_revision = '347efdaf84fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('id', UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('sport', sa.String(length=40), nullable=False),
    sa.Column('league', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('abbreviation', sa.String(length=12), nullable=True),
    sa.Column('slug', sa.String(length=120), nullable=True),
    sa.Column('location', sa.String(length=80), nullable=True),
    sa.Column('color', sa.String(length=8), nullable=True),
    sa.Column('alternate_color', sa.String(length=8), nullable=True),
    sa.Column('logo', sa.String(length=400), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sport', 'league', 'external_id', name='uq_team')
    )
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teams_external_id'), ['external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_teams_league'), ['league'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teams_league'))
        batch_op.drop_index(batch_op.f('ix_teams_external_id'))

    op.drop_table('teams')
    # ### end Alembic commands ###
