"""events table

Revision ID: 347efdaf84fa
Revises:
Create Date: 2026-06-20 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID


# revision identifiers, used by Alembic.
revision = '347efdaf84fa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('sport', sa.String(length=40), nullable=False),
    sa.Column('league', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('short_name', sa.String(length=80), nullable=True),
    sa.Column('home_team', sa.String(length=120), nullable=False),
    sa.Column('home_abbr', sa.String(length=12), nullable=True),
    sa.Column('away_team', sa.String(length=120), nullable=False),
    sa.Column('away_abbr', sa.String(length=12), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('winner_side', sa.String(length=8), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_external_id'), ['external_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_events_league'), ['league'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_status'))
        batch_op.drop_index(batch_op.f('ix_events_league'))
        batch_op.drop_index(batch_op.f('ix_events_external_id'))

    op.drop_table('events')
    # ### end Alembic commands ###
